#!/bin/bash -e
export yellow="\033[33m"
export red="\033[31m"
export green="\033[32m"
export done="\033[0m"
echo -e "${green}宁在做宁🐎的美梦，像宁这样的老色批还敢有如此想法着实令人佩服{done}"
echo -e "${green}You haven't girlfriend,never have{done}"
