#!/usr/bin/env python3

import requests
import json
import sys
import argparse


def suo(text:str):
    r = requests.post('https://lab.magiconch.com/api/nbnhhsh/guess',data={'text':str(text)})
    tran = ""
    try:
        trans = json.loads(r.text)[0]['trans']
    except KeyError:
        print('可能暂时没有这个缩写！')
        print(e)
    for i in trans:
        if len(trans) == 1:
            return i
            break
        else:
            tran += i+"，"

    return tran[:-1]
    
parser = argparse.ArgumentParser(description="一个转换缩写的工具")
parser.add_argument("text")
parser.parse_args()
text = parser.parse_args().text
print(suo(text))
