#!/bin/bash
export link="www.baidu.com"
reslut=$(curl -s "$link")
if [ not"$reslut" == "not" ]; then
  echo -e "\033[41;30m                             当前国内通用网络异常                                \033[0m"
else
  echo -e "\033[42;30m                             当前国内通用网络良好                                \033[0m"
fi
