#!/bin/bash -e
#GitHub: https://github.com/edges5352
#Website: https://powerlean.top
#Owner: Powerlean (2020)
######################################
export version="12"

#目标地址#
export test_update="powerlean.top/blob/poco.log"
export list_url="powerlean.top/blob/source.list"
export site="powerlean.top/"
export site_404="powerlean.top/404"
export bin=`which bash | sed 's/bash//g'`
export blob="blob/"
export setup="mv ${2} ${bin}"
export output="/dev/null"
#毫无作用的乐色#
function progress {
  point="echo -n ."
  sec="0.2"
  sleep $sec
  $point
  sleep $sec
  $point
  sleep $sec
  echo "."
  sleep $sec
}

#特殊字符#
export yellow="\033[33m"
export red="\033[31m"
export green="\033[32m"
export done="\033[0m"

#字符变量#
#中文
export error_remove_cn="echo -e ${red}无效操作 ${choice}${done}"
export remove_cn="确定要移除此文件吗？"
export void_cn="echo -e ${red}无效操作 ${1}${done}"
export search_cn="echo -n -e  正在向${yellow}${site}${blob}${2}${done}核对报头"
export void_found_cn="echo -e ${red} 此文件不存在或暂不提供下载，抱歉...${done}"
export try_download_cn="echo -n 核对完成，尝试获取文件主体"
export file_fail_cn="echo -e ${red}获取失败:文件${yellow}${2}${done}不存在或因目标停止传输${done}"
export firewall_fail_cn="echo -e ${red}获取失败:请检索网络或防火墙设置${done}"
export done_download_cn="echo -e 文件${yellow}${2}${done}获取完成"
export unknow_cn="echo -e 出现不明原因错误，若您觉得这个问题不该出现，请将其反馈至${yellow}https://powerlean.top/issues${done}"
export hook_cn="echo -n 正在设定触发器"
export done_setup_cn="echo -e ${yellow}${2}${done}设定完成"
export error_found_cn="echo -e ${red}无法移除${2}：文件或目录不存在${done}"
export install_info_cn="从目标地址获取指定文件"
export remove_info_cn="删除指定的可执行文件"
export help_info_cn="查询有效参数"
export intro_info_cn="poco是Powerlean资源存储分发库附带的下载安装文件管理程序"
export not_input_cn="echo -e ${red}请指定一个目标文件${done}"
export come_cn="来自"
export size_cn="总计大小"
export install_cn="确定要获取此文件吗?"
export error_get_cn="echo -e ${red}无效操作 ${choice}${done}"
export unit_cn="字符"
export list_info_cn="列出所有可供下载的文件"
export request_cn="正在从远端拉取请求"
export force_update_cn="echo -e ${red}正在进行必要的强制更新,请勿终止程序${done}"
#English
export install="Are you sure that you want to download this file?"
export come="From"
export void="echo -e ${red}Invalid operation ${1}${done}"
export search="echo -n -e  Checking header from ${yellow}${site}${blob}${2}${done}"
export void_found="echo -e ${red} No such file or cannot be collecting,sorry...${done}"
export try_download="echo -n Check done,start collecting"
export file_fail="echo -e ${red}Something error:file${yellow}${2}${done} is not exist or progress interruption${done}"
export firewall_fail="echo -e ${red}Something error:please check your network and firewall settings${done}"
export done_download="echo -e File ${yellow}${2}${done} is downloaded"
export unknow="echo -e Something wrong,if you think it is a problem,please send feedback to ${yellow}https://powerlean.top/issues${done}"
export hook="echo -n Setting hook function"
export done_setup="echo -e ${yellow}${2}${done} is already set done"
export remove="Are you sure that you want to remove this file?"
export error_remove="echo -e ${red}Invalid operation ${choice}${done}"
export error_found="echo -e ${red}cannot remove $2: No such file or directory${done}"
export install_info="Get a file"
export remove_info="Delete a file which you don't need"
export help_info="Get help for poco"
export intro_info="POCO is a installation management script cluded with Powerlean Online Repository"
export not_input="echo -e ${red}Please specify a file name${done}"
export size="Total Size"
export error_get="echo -e ${red}Invalid operation ${choice}${done}"
export unit="characters"
export list_info="List all files which can be download"
export request="To remote:Pulling request"
export force_update="echo -e ${red}You are below the latest version,force update will start at moment${done}"
#语言设定
#LANG="zh_CN.UTF-8"#取消该注释将程序设定为中文
if [ $LANG == "zh_CN.UTF-8" -o $LANG == "zh_TW.UTF-8" -o $LANG == "zh_HK.UTF-8" -o $LANG == "zh_SG.UTF-8" ]; then
  export list_info=$list_info_cn
  export unit=$unit_cn
  export size=$size_cn
  export install=$install_cn
  export come=$come_cn
  export intro_info=$intro_info_cn
  export error_found=$error_found_cn
  export void=$void_cn
  export search=$search_cn
  export void_found=$void_found_cn
  export try_download=$try_download_cn
  export file_fail=$file_fail_cn
  export firewall_fail=$firewall_fail_cn
  export done_download=$done_download_cn
  export unknow=$unknow_cn
  export hook=$hook_cn
  export done_setup=$done_setup_cn
  export remove=$remove_cn
  export error_remove=$error_remove_cn
  export install_info=$install_info_cn
  export remove_info=$remove_info_cn
  export help_info=$help_info_cn
  export not_input=$not_input_cn
  export error_get=$error_get_cn
  export request=$request_cn
  export force_update=$force_update_cn
fi
#检测更新
  lastest_version=`curl -s ${site}${blob}${0}.log`
if [[ "$version" -ne "$lastest_version" ]]; then
  ${force_update}
  wget ${site}${blob}${0} 1>"$output" 2>&1 | progress
  if [ -f "$0" ]; then
    mv $0 $bin
    chmod +x $bin/$0
    "$0 help"
  else
    ${unknow}
  fi
fi
#主体(一扇区)
if [ "$1" == "install" -o "$1" == "i" ]; then #因玄学问题取消一元运算符
  if [ not"$2" == "not" ]; then
    ${not_input}
    exit 2
  fi
  ${search}
  progress
  not_found=`curl ${site_404}`
  try=`curl -s ${site}${blob}${2}`
  if [ "$try" == "$not_found" ]; then
    ${void_found}
    exit 2
  else
    ${try_download}
    progress
    echo "───────────────────────────────"
    echo -e "${2}         ${size}:${#try} ${unit}"
    echo ""
    echo -e "${come}:${yellow}${site}${blob}${2}${done}"
    echo "───────────────────────────────"
    read -p "$install [Y/n]: " choice
        if [ "$choice" == "y" -o "$choice" == "Y" ]; then
          wget ${site}$blob/$2
        elif [ "$choice" == "n" -o "$choice" == "N" ]; then
          exit 0
        else
          ${error_get}
          exit 1
       fi
    case $? in
      "8")
        ${file_fail}
        exit 2
    ;;
      "4")
        ${firewall_fail}
        exit 3
    ;;
      "0")
        ${done_download}
    ;;
        *)
        ${unknow}
        exit 1
    esac
${hook}
progress
${setup}
chmod +x $bin/$2
${done_setup}
  fi 
elif [ "$1" == "remove" -o "$1" == "r" ]; then
  if [ not"$2" == "not" ]; then
    ${not_input}
    exit 2
  fi
  if [ -f $bin/$2 ]; then
    read -p "$remove [Y/n]: " choice
    if [ "$choice" == "y" -o "$choice" == "Y" ]; then
      rm -rf $bin/$2 #因为不明文件属性，故强制递归
    elif [ "$choice" == "n" -o "$choice" == "N" ]; then
      exit 0
    else
      ${error_remove}
      exit 1
    fi
  else
    ${error_found}
  fi
elif [ "$1" == "list" -o "$1" == "l" ]; then
  echo -n "${request}"
  progress
  curl ${list_url}
elif [ "$1" == "help" -o "$1" == "h" ]; then
  echo "poco       version:${version}"
  echo "${intro_info}"
  echo ""
  echo -e "${green}i${done}nstall       ${install_info}"
  echo -e "${green}r${done}emove        ${remove_info}"
  echo -e "${green}h${done}elp          ${help_info}"
  echo -e "${green}l${done}ist          ${list_info}"
else
  ${void}
fi
